remote_host:
  username: test_user
  password: test_pass
  server: www.timothyfisher.com
  path: /remote/test
  file_perm: 0644
  dir_perm: 0755

properties:
  local_path: .
  dirs_to_sync: ['app', 'config', 'db', 'public', 'test']
  ignore_list: [!ruby/regexp '/CVS/', 
                !ruby/regexp '/SVN/', 
                !ruby/regexp '/ext-1/', 
                !ruby/regexp '/yui/', 
                !ruby/regexp '/tinymce/']
  


